[package]
name = "dfc_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.3.1"
ic-cdk-macros = "0.3.1"
uuid = { version = "0.8", features = ["v4"] }
